name: Execute Open Brewery Automation Tests
on:
    workflow_call:
        inputs:
            cucumber-tag:
                required: true
                description: Add the cucumber tag of the tests you would like to run.
                type: string

jobs: 
    execute-component-tests:
        name: Execute Component Tests
        runs-on: ubuntu-22.04
        permissions: 
            actions: write
            contents: write
        steps:
        - uses: actions/checkout@v4

        - name: Set Up Node
          uses: ./.github/actions/setup-node
          with:
            working-directory: ./automation
        
        - name: Generate .ENV file
          working-directory: ./automation
          shell: bash
          run: |
            echo 'API_URL=${{ vars.API_URL }}' > .env

        - name: Execute Tests
          working-directory: ./automation
          run: 
            npx cucumber-js --tags "${{ inputs.cucumber-tag }}"
        
        - name: upload artifact
          if: always()
          uses: actions/upload-artifact@v4
          with: 
            path: 'automation/reporting/cucumber-report/'
        
        - name: Load test report history
          uses: actions/checkout@v4
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages
  
        - name: Build test report
          uses: simple-elf/allure-report-action@v1.7
          if: always()
          with:
            gh_pages: gh-pages
            allure_history: allure-history
            allure_results: automation/reporting/allure/allure-results
  
        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history





